name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # 当推送到main分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检查代码库
      - name: Checkout repository
        uses: actions/checkout@v2

      # 登录到Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username:1103412707@qq.com
          password: lsdc@1003

      # 构建Docker镜像
      - name: Build Docker image
        run: docker build -t wojiaomht/astro:$(date +%s)

      # 推送Docker镜像到Docker Hub
      - name: Push Docker image
        run: docker push wojiaomht/astro:$(date +%s)

